# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha de recibido', models.DateTimeField()),
                ('Fecha enviado', models.DateTimeField()),
                ('observaciones', models.TextField()),
                ('usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('Fecha de entrada', models.DateField()),
                ('Fecha de finalizacion', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('numero_folios', models.CharField(max_length=10)),
                ('completado', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'expediente',
                'verbose_name_plural': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('usuario', models.IntegerField()),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apie.Expediente')),
            ],
            options={
                'verbose_name': 'observacion',
                'verbose_name_plural': 'observaciones',
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.CharField(max_length=100)),
                ('cumplido', models.SmallIntegerField(default=0)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apie.Expediente')),
            ],
            options={
                'verbose_name': 'requisito',
                'verbose_name_plural': 'requisitos',
            },
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apie.Expediente'),
        ),
    ]
